### ISSUE TITLE
leg switching problem

### ISSUE THREAD

**Issue by maorp** [AljazBozic/NeuralGraph#4]
Hi Aljaz, started testing the method on a new dataset. i trained graph only for 540000 iters and i get good but also some bad deformations. the data is a person walking for 100 frames, and i deform the gt mesh from frame 0 to all other 99 frames (I'm using similar code used in surface Consistency and the newly added denseTracking). on several frames the legs are deformed such that they get switched from left to right. i see the graph nodes also switch. I suspect that its due to the symmetry and the harmonic movement. some pairs in the batch have the right and left leg close and it drives the graph to this bad local minimum. I'm thinking about a possible solution by adding a collision \ mesh stretch (ARAP) \ semantic loss to prevent this. ill try to contribute and add it...
i can share the data if needed and attached ply with the problem for close inspection:
[mesh_trans.zip](https://github.com/AljazBozic/NeuralGraph/files/6814394/mesh_trans.zip)
frame 0 deformed to 30 - still good:
![image](https://user-images.githubusercontent.com/11231999/125523538-8efe965e-6d45-4b74-84e1-b3500ea50a7d.png)
frame 0 deformed to 31 - leg switch:
![image](https://user-images.githubusercontent.com/11231999/125523791-a4ad67a2-2cd4-4c2a-9770-8abe990bc822.png)
zoomed:
![image](https://user-images.githubusercontent.com/11231999/125523920-2ed99c06-3f15-4b01-a241-b32b29905c06.png)
zoomed with graph:
![image](https://user-images.githubusercontent.com/11231999/125524207-2c106b97-e03b-4c82-a401-4a9346409394.png)
zoomed good frame, see the pink, light green and yellow nodes are now back to left:
![image](https://user-images.githubusercontent.com/11231999/125524397-e38bd4cb-a071-4e78-86be-fc33d60de1a5.png)

**Comment by AljazBozic** [comment]
Hi @maorp! Thank you for the detailed explanation! 

In my experience these kind of issues can result from problems in data preprocessing, so that's the first things I would check:
- for uniform/near surface samples of all meshes, the inside values should be always inside the mesh (if mesh is not completely watertight at some time step, the inside points will also leak into free space)
- the global scale of the mesh might need to be adjusted (inside `scripts/process_mesh_local.sh`, the argument `-scale 0\.35`); ideally the uniform bounding box is tight (to have enough inside samples), but no vertex is outside the bounding box (since that again leads to leakage of inside points in free space)

Beside that, you might need to ensure to have enough meshes in temporal domain. A lot of consistency (and successful convergence) comes from inductive bias of 3d encoder, predicting similar graph values for similar inputs. Therefore, if you run the method on completely disconnected mesh snapshots, it will be harder to converge to consistent solution.

These are all things that can help. There are of course challenging scenarios where tracking can fail (like large deformation change in few snapshot), semantics could definitely help there to re-localize corresponding parts globally.

Best,
Aljaz

**Comment by AljazBozic** [comment]
I'll close the issue for now, let me know if you have further questions.

Best,
Aljaz
